[project]
name = "pacman"
version = "0.1.5"
description = "PacMan clone project."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mazegenerator",
    "mlx",
    "pydantic>=2.13.5",
]

[tool.uv.sources]
mazegenerator = { path = "wheels/mazegenerator-2.1.0-py3-none-any.whl" }
mlx = { path = "wheels/mlx-2.4-py3-none-any.whl" }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 79
[tool.ruff.lint]
select = ["E", "F", "B", "I"]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
exclude = [
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
]

[[tool.mypy.overrides]]
module = ["mlx", "mazegenerator"]
ignore_missing_imports = true
